export const ProductData = [
  {
    id: 1,
    name: "Cát vệ sinh cho mèo",
    cost: 60000,
    remainProduct: 100,
    soldProduct: 999,
    tag: ["mèo", "cat", "sand"],
    user: "Mèo",
    status: "Còn",
    // status: {ProductData.map((e) => {
    //   e.remainProduct > 0 ? "Còn" : "Đã hết";
    // })},
    date: "2022-02-25",
  },
  {
    id: 2,
    name: "Thức ăn cho mèo",
    cost: 100000,
    remainProduct: 252,
    soldProduct: 1234,
    tag: ["mèo", "cat", "food"],
    user: "Mèo",
    status: "Đã hết",
    date: "2022-02-03",
  },
  {
    id: 3,
    name: "Sữa tắm cho mèo",
    cost: 125000,
    remainProduct: 26,
    soldProduct: 35,
    tag: ["mèo", "cat", "soap"],
    user: "Mèo",
    date: "2021-02-26",
    status: "Đã hết",
  },
  {
    id: 4,
    name: "Soup thưởng cho mèo",
    cost: 10000,
    remainProduct: 243,
    soldProduct: 863,
    tag: ["mèo", "cat", "soup"],
    user: "Mèo",
    date: "2022-8-26",
    status: "Đã hết",
  },
  {
    id: 5,
    name: "Pate cho mèo",
    cost: 10000,
    remainProduct: 258,
    soldProduct: 1563,
    tag: ["mèo", "cat", "pate"],
    user: "Mèo",
    date: "2021-11-30",
    status: "Đã hết",
  },
  {
    id: 6,
    name: "Cỏ mèo",
    cost: 30000,
    remainProduct: 15,
    soldProduct: 90,
    tag: ["mèo", "cat", "grass"],
    user: "Mèo",
    date: "2021-03-24",
    status: "Đã hết",
  },
  {
    id: 7,
    name: "Trụ cào móng cho mèo",
    cost: 20000,
    remainProduct: 10,
    soldProduct: 20,
    tag: ["mèo", "cat", "toys"],
    user: "Mèo",
    date: "2021-08-29",
    status: "Đã hết",
  },
  {
    id: 8,
    name: "Bát ăn cho mèo",
    cost: 50000,
    remainProduct: 65,
    soldProduct: 425,
    tag: ["mèo", "cat", "sand"],
    user: "Mèo",
    date: "2021-08-16",
    status: "Đã hết",
  },
  {
    id: 9,
    name: "Đồ chơi cho mèo",
    cost: 42000,
    remainProduct: 200,
    soldProduct: 452,
    tag: ["mèo", "cat", "sand"],
    user: "Mèo",
    date: "2021-08-02",
    status: "Đã hết",
  },
  {
    id: 10,
    name: "Thức ăn cho chó",
    cost: 120000,
    remainProduct: 824,
    soldProduct: 3542,
    tag: ["mèo", "cat", "sand"],
    user: "Chó",
    date: "2021-01-03",
    status: "Đã hết",
  },
  {
    id: 11,
    name: "Kìm cắt móng cho mèo",
    cost: 17000,
    remainProduct: 35,
    soldProduct: 138,
    tag: ["mèo", "cat", "sand"],
    user: "Mèo",
    date: "2021-09-10",
    status: "Đã hết",
  },
  {
    id: 12,
    name: "Ổ mèo",
    cost: 225000,
    remainProduct: 60,
    soldProduct: 238,
    tag: ["mèo", "cat", "sand"],
    user: "Mèo",
    date: "2021-07-06",
    status: "Đã hết",
  },
  {
    id: 13,
    name: "Pate cho chó",
    cost: 250000,
    remainProduct: 536,
    soldProduct: 2458,
    tag: ["mèo", "cat", "sand"],
    user: "Chó",
    date: "2021-09-09",
    status: "Đã hết",
  },
  {
    id: 14,
    name: "Thức ăn hamster",
    cost: 43000,
    remainProduct: 25,
    soldProduct: 365,
    tag: ["mèo", "cat", "sand"],
    user: "Chuột",
    date: "2021-08-04",
    status: "Đã hết",
  },
  {
    id: 15,
    name: "Wheel hamster",
    cost: 58000,
    remainProduct: 100,
    soldProduct: 999,
    tag: ["mèo", "cat", "sand"],
    user: "Chuột",
    date: "2021-02-27",
    status: "Đã hết",
  },
];
